#!/bin/bash
set -e

get_rootfs(){
	image="$1"
	bundle=rootfs
	userns_uid=$(cat config.json | jq '.linux.uidMappings' | jq --raw-output '.[0].hostID' || echo "")

	if [[ -z "$image" ]]; then
		# get the basename of the current directory
		image=$(basename "$(pwd)")
	fi

	docker pull --disable-content-trust=false "$image" || {
		image="r.j3ss.co/${image}"
		docker pull --disable-content-trust=false "$image"
	}

	shortname=${image%%:*}
	if echo "$shortname" | grep -q "/" ; then
		shortname=${shortname#*/}
	fi

	id=$(docker create "$image" || docker create "$image" sh)
	docker export "$id" > "${shortname}.tar"

	# remove the container you created
	docker rm -f "$id"

	if [[ -d "$bundle" ]]; then
		sudo rm -rf "$bundle"
	fi

	mkdir -p "$bundle"
	sudo tar -C "$bundle" -xf "${shortname}.tar"

	# chown for userns
	if [ ! -z "$userns_uid" ] && [ "$userns_uid" != "null" ]; then
		sudo chown -R "${userns_uid}":"${userns_uid}" "${bundle}"
	fi

	rm -f "${shortname}.tar"
}

get_rootfs $@
